# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.guest:
        class: AppBundle\Repository\GuestRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: [ AppBundle\Entity\Guest ]

    app.repository.image:
        class: AppBundle\Repository\ImageRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: [ AppBundle\Entity\Image ]